### ISSUE TITLE
how to get these parameter

### ISSUE THREAD

**Issue by desthon** [Mantan21/Genshin-Impact-Wish-Simulator#100]
it seem impossible to just try to get them, so how to?
![image](https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/assets/141696937/200cb4e7-4088-4204-86c4-e54b28a1cb4a)

**Comment by AguzzTN54** [comment]
`splashArt` and `wishCard` offset can be obtained from Custom Banner feature.

1. After you run the Dev Server, navigate to (?) -> Custom Banner and create a new Custom Banner. Then, insert your images.

https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/assets/13815468/201dec92-f5cc-4f1f-b519-a94b64b80d29

2. Once done, click the "**Adjust Splash Art**" Button. After setting the position, the data you're looking for will be logged in the Console (CTRL + Shift + i).

https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/assets/13815468/5a5b5179-83bc-42fd-a116-8b1149b20fa9

**Comment by desthon** [comment]
ok，i see and thank you
