### ISSUE TITLE
Setting Banner

### ISSUE THREAD

**Issue by Ksuscara** [Mantan21/Genshin-Impact-Wish-Simulator#103]

**Comment by Ksuscara** [comment]
Hello so my bug is uhm when i open the setting for the luck rating its just the banner upsidedown 
Ps: Hello im back

**Comment by AguzzTN54** [comment]
Can you tell me what device and browser you are using?
And have you tried using a different browser?

**Comment by Ksuscara** [comment]
Yes and it doesnt work
Ios and google chrome

**Comment by Ksuscara** [comment]
So whats going on?

**Comment by AguzzTN54** [comment]
I need some time to investigate this issue due to the limitations of the devices available for testing.
But I have made some changes, so how about now? Is it working?

**Comment by Ksuscara** [comment]
Oh my your an expert at website bugs its works thank you so much!
