### ISSUE TITLE
Complete German Translation + Item Translation

### ISSUE THREAD

**Issue by Alextocode** [Mantan21/Genshin-Impact-Wish-Simulator#105]
Adding a new Github issue for this. 
I take care of it myself.

**Comment by Alextocode** [comment]
Hi @Mantan21,

seems I can not add branches / pull requests to your repository.
I made a fork of my changes therefore:
https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/pull/106/files

Any chance you can get this merged into your master?
Btw good job, I play with your tool a lot, that's why I now volunteered and spent a few hours to compile the translation to Germany.

Unfortunately the Chronicle Wish Banner I could not translate so far since the official German texts are currently unavailable ingame or somewhere else.
Everything else I translated. I also added some minor fixes to existing German translation and also to the English US File.

Hope it helps.

Cheers!

Alex_

**Comment by AguzzTN54** [comment]
Whoa, sorry for the late response.
Thank you so much, I really appreciate it.
I'll check it out and push it to production right away.
