### ISSUE TITLE
Bug: Awkward behaviour of banner settings in Firefox

### ISSUE THREAD

**Issue by Alextocode** [Mantan21/Genshin-Impact-Wish-Simulator#107]
Hi there
In Firefox browser on PC one is unable to alter the settings of banners because when flipping to the settings the actual banner flips as well covering the settings.
This does not happen in Google Chrome.

It looks likes this:
![grafik](https://github.com/user-attachments/assets/225f95a8-9772-4788-8463-7f8695ee8fed)

Maybe this can be fixed, since I am a Firefox user - at least on PC.
😄 

Cheers!

Alex

**Comment by AguzzTN54** [comment]
LOL, I didn't realize that all this time.

It seems like many other players have experienced the same issue. Thank you for reporting this. if you hadn't, I would never have known about this.
