### ISSUE TITLE
Meteor Animation Failed to Load  

### ISSUE THREAD

**Issue by Bxnnily** [Mantan21/Genshin-Impact-Wish-Simulator#37]
Meteor animation failed to load. I tried on safari and it doesn't work so I tried chrome. It doesn't work too. I then switched to my android tablet and it didn't work either.

**Comment by AguzzTN54** [comment]
Okay, I'll take a look..
Does the animation fail to load from the first time visiting the web  ?

**Comment by Bxnnily** [comment]
No, it happens every time I pull.

**Comment by AguzzTN54** [comment]
Sorry for taking so long, I've changed some parts of the code, I think it should work in latest chrome, firefox, opera and  safari 15
Can you test it again in your side ? I would appreciate that.

**Comment by Bxnnily** [comment]
Unfortunately, the meteor still fails to load and I've tried on multiple browsers: including the ones you said.

**Comment by AguzzTN54** [comment]
Can you try this one  [https://7bae280e.wishsimulator.pages.dev/](https://7bae280e.wishsimulator.pages.dev/) ?
I've added a box to show the video log, can you send a screenshot containing this log? it should looks like this.

![image](https://user-images.githubusercontent.com/13815468/189480785-c2d89735-49a2-4e93-ae07-5a48b56079d1.png)

**Comment by Bxnnily** [comment]
Ok!

![image](https://user-images.githubusercontent.com/112222561/189491833-9512a566-2892-4fa7-9ee4-6dc40bc4b07d.png)

**Comment by AguzzTN54** [comment]
I see. maybe because safari doesn't fully support webm video format, so I change it to mp4. I hope this can solve the problem

**Comment by Bxnnily** [comment]
At first there was a white screen, but after wishing a few more times, it worked! Ok, nevermind about working. It stopped working again. Here is a video about what if looks like: https://user-images.githubusercontent.com/112222561/189550528-8a228309-5ee4-4645-be71-8d6bfbf334c6.MOV

**Comment by Bxnnily** [comment]
It works only a few times but then stopped working. I refreshed my screen a few times and it only show a white screen. When it worked, it shows in a form of a video where you can pause and replay. It will take you go th result after clicking X. 

The white screen only goes away when I refresh and I can only see my results through history.

**Comment by ivyybbz** [comment]
mine won't load to i also tried on chrome and safari but it doesn't work

**Comment by AguzzTN54** [comment]
I think it's fixed now.
