### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by Ksuscara** [Mantan21/Genshin-Impact-Wish-Simulator#93]
The wish meteor animation is failed to load why plss help

**Comment by AguzzTN54** [comment]
If you are in the iOS ecosystem, some functions may not work properly. I'm still working on finding a solution to this problem.

**Comment by Ksuscara** [comment]
Ok tysm its really making me a lil upset cuz idk if its a 5 star or 4 star so thank youu

**Comment by Ksuscara** [comment]
And yes im on ios

**Comment by Ksuscara** [comment]
By the way do you have another wish simulator website? That i can play on that has a wish or any other wish simulator while waiting for the meteor fix

**Comment by AguzzTN54** [comment]
Have you tried this [https://gi-wish-simulator.uzairashraf.dev/](https://gi-wish-simulator.uzairashraf.dev/) ?

I don't know much about other simulator sites, but I think there are already many similar apps that you can find if you search for them.

**Comment by Ksuscara** [comment]
Thank you

**Comment by Ksuscara** [comment]
Hello are u trying to fix it cuz its really bugging me

**Comment by Ksuscara** [comment]
Hi when do you think this will get fixed:/

**Comment by AguzzTN54** [comment]
Sorry, I still have no clue.

But, can you tell me about your experience while pulling from these sites?
- [https://gi-wish-simulator.uzairashraf.dev/](https://gi-wish-simulator.uzairashraf.dev/)
- [https://primoprod.vercel.app/](https://primoprod.vercel.app/)
- [https://bluestixs.github.io/WishSim/](https://bluestixs.github.io/WishSim/)
- [https://genshin-wish-simulator-khaki.vercel.app/](https://genshin-wish-simulator-khaki.vercel.app/)

Do the meteor animations show up or not?
I'll try to use the same code from the site that works well.

**Comment by Ksuscara** [comment]
I think you should use the primoprod one its a lil better

**Comment by Ksuscara** [comment]
I have played them but its so lagyy

**Comment by Ksuscara** [comment]
Can You Fix It Almost?!

**Comment by AguzzTN54** [comment]
I've made a small change. How does it look now?

**Comment by Ksuscara** [comment]
Sorry Still Not Working.

**Comment by AguzzTN54** [comment]
![image](https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/assets/13815468/d798ad0a-0419-41db-970d-d4b25399f963)
Is this alert still appearing, or are you experiencing a different issue?

**Comment by Ksuscara** [comment]
Yes!

**Comment by Ksuscara** [comment]
Thats Exactly Whats Happening

**Comment by AguzzTN54** [comment]
Okay.. I'm still trying..

I've tested this on BrowserStack and LambdaTest, and it seems to be working now. However, I still don't know about the real experience since I don't have access to an iOS device. 
Sorry, I hope you can be patient with this problem.

**Comment by Ksuscara** [comment]
ITS FIXED!

**Comment by Ksuscara** [comment]
THANK YOU!

**Comment by AguzzTN54** [comment]
Oh, really?
Well, in that case, I think I can close this issue. Thank you for your patience all this time.
