### ISSUE TITLE
ask for approve

### ISSUE THREAD

**Issue by cyanial** [Mantan21/Genshin-Impact-Wish-Simulator#95]
Hi!

I edit you project to support custom item picker. Then I use the project in high school class to randomly pick students to ask questions. 

Can I get the approve to clone your project and publish my edited version to the public.

Thank you for your project.

**Comment by AguzzTN54** [comment]
Oh, sure.
Feel free to unleash your creativity. I'd be happy to see someone inspired by my works.
And don't forget to put the credit .

**Comment by youmengyi404** [comment]
你好
我下载了文件genish-impact-win32-x64，打开了exe文件但一直卡在了初始画面
